#pragma once
#include "basic_types.h"

#define INVALID_APIC_ID 0xff
#define INVALID_X2APIC_ID 0xffffffff

enum {
    APIC_ID  = 0x20,
    APIC_VER = 0x30,
    APIC_TPR = 0x80,
    APIC_APR = 0x90,
    APIC_PPR = 0xA0,
    APIC_EOI = 0xB0,
    APIC_RRD = 0xC0,
    APIC_LDR = 0xD0,
    APIC_DFR = 0xE0,
    APIC_SPURIOUS = 0xF0,
    APIC_ISR0 = 0x100,
    APIC_ISR1 = 0x110,
    APIC_ISR2 = 0x120,
    APIC_ISR3 = 0x130,
    APIC_ISR4 = 0x140,
    APIC_ISR5 = 0x150,
    APIC_ISR6 = 0x160,
    APIC_ISR7 = 0x170,
    APIC_TMR0 = 0x180,
    APIC_TMR1 = 0x190,
    APIC_TMR2 = 0x1A0,
    APIC_TMR3 = 0x1B0,
    APIC_TMR4 = 0x1C0,
    APIC_TMR5 = 0x1D0,
    APIC_TMR6 = 0x1E0,
    APIC_TMR7 = 0x1F0,
    APIC_IRR0 = 0x200,
    APIC_IRR1 = 0x210,
    APIC_IRR2 = 0x220,
    APIC_IRR3 = 0x230,
    APIC_IRR4 = 0x240,
    APIC_IRR5 = 0x250,
    APIC_IRR6 = 0x260,
    APIC_IRR7 = 0x270,
    APIC_ESR = 0x280,
    APIC_LVT_CMCI = 0x2F0,
    APIC_ICRLO = 0x300,
    APIC_ICRHI = 0x310,
    APIC_LVT_TIMER = 0x320,
    APIC_LVT_THERMAL = 0x330,
    APIC_LVT_PMC = 0x340,
    APIC_LVT_LINT0 = 0x350,
    APIC_LVT_LINT1 = 0x360,
    APIC_LVT_ERR = 0x370,
    APIC_INITIAL_COUNT = 0x380,
    APIC_CURRENT_COUNT = 0x390,
    APIC_TIMER_DIVIDE = 0x3E0,
};

enum {
    APIC_IPI_VECTOR_SHIFT = 0,
    APIC_IPI_VECTOR_MASK = ~(0xffull << APIC_IPI_VECTOR_SHIFT),

    APIC_IPI_DELMODE_SHIFT = 8,
    APIC_IPI_DELMODE_MASK = ~(3ull << APIC_IPI_DELMODE_SHIFT),

    APIC_IPI_DESTMODE_SHIFT = 11,
    APIC_IPI_DESTMODE_MASK = ~(1ull << APIC_IPI_DESTMODE_SHIFT),

    APIC_IPI_DELIVERY_STATUS_SHIFT = 12,
    APIC_IPI_DELIVERY_STATUS_MASK = ~(1ull << APIC_IPI_DELIVERY_STATUS_SHIFT),

    APIC_IPI_LEVEL_SHIFT = 14,
    APIC_IPI_LEVEL_MASK = ~(1ull << APIC_IPI_LEVEL_SHIFT),

    APIC_IPI_TRIGGER_SHIFT = 15,
    APIC_IPI_TRIGGER_MASK = ~(1ull << APIC_IPI_TRIGGER_SHIFT),

    APIC_IPI_DEST_SHIFT = 18,
    APIC_IPI_DEST_MASK = ~(1ull << APIC_IPI_DEST_SHIFT),

    APIC_IPI_DEST_APICID_SHIFT = 56,

    APIC_IPI_DELMODE_FIXED = 0ull,
    APIC_IPI_DELMODE_LOW_PRI = 1ull << APIC_IPI_DELMODE_SHIFT,
    APIC_IPI_DELMODE_SMI = 2ull << APIC_IPI_DELMODE_SHIFT,
    APIC_IPI_DELMODE_NMI = 4ull << APIC_IPI_DELMODE_SHIFT,
    APIC_IPI_DELMODE_INIT = 5ull << APIC_IPI_DELMODE_SHIFT,
    APIC_IPI_DELMODE_INIT_DEASSERT = 5ull << APIC_IPI_DELMODE_SHIFT,
    APIC_IPI_DELMODE_SIPI = 6ull << APIC_IPI_DELMODE_SHIFT,

    APIC_IPI_DESTMODE_PHYSICAL = 0,
    APIC_IPI_DESTMODE_LOGICAL = 1ull << APIC_IPI_DESTMODE_SHIFT,


    APIC_IPI_LEVEL = 1ull << APIC_IPI_LEVEL_SHIFT,

    APIC_IPI_TRIGGER_EDGE = 0,
    APIC_IPI_TRIGGER_LEVEL = 1ull << APIC_IPI_TRIGGER_SHIFT,

    APIC_IPI_DEST_APICID = 0,
    APIC_IPI_DEST_SELF = 1ull << APIC_IPI_DEST_SHIFT,
    APIC_IPI_DEST_ALL_INCLUDING_SELF = 2ull << APIC_IPI_DEST_SHIFT,
    APIC_IPI_DEST_ALL_EXCLUDING_SELF = 3ull << APIC_IPI_DEST_SHIFT,
};

void ApicWrite(uint32 reg, uint64 val);
uint64 ApicRead(uint32 reg);
void ApicIPI(uint32 apicId, uint32 flags);
uint32 MyApicId(void);
